kind: Service

apiVersion: v1beta3

metadata:
  name: frontend

  labels:
    name: frontend
    group: kubersample

spec:
  ports:
  - port: 8080
    targetPort: 4567
    protocol: TCP

  publicIPs:
  - 54.187.97.90
  - 172.20.0.10

  selector:
    name: frontend
    group: kubersample
