kind: Service

apiVersion: v1beta3

metadata:
  name: frontend

  labels:
    name: frontend
    group: kubersample

spec:
  ports:
  - port: 8080
    targetPort: 4567
    protocol: TCP

  publicIPs:
  - 52.24.151.102
  - 172.20.0.11

  selector:
    name: frontend
    group: kubersample
